name = "norest-folha-pagamento"
main = "src/worker.js"
compatibility_date = "2024-04-05"

[[kv_namespaces]]
binding = "DB"
id = "e5c47cf489874e2fad8501f4339eab71"
preview_id = "19aae6752e1b4ef0bf0088727f80a3fe"

# Secrets (REGISTRATION_TOKEN) devem ser configurados via:
# wrangler secret put REGISTRATION_TOKEN